spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurityDB
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ## Enable generate-ddl property or change ddl-auto to create for automatic tables creation
      ddl-auto: update
      ##generate-ddl: true

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
